### ISSUE TITLE
Where is mac version?

### ISSUE THREAD

**Issue by NICKNAME5166** [BarsTiger/D0CXUN7R4C3#1]
Лень было ещё в дмг файл собрать? Вроде ж питон, не сложно...

**Comment by BarsTiger** [comment]
Не хочу bootloader'ы под другие таргет-системы собирать 🥰

**Comment by BarsTiger** [comment]
p.s. к тому же, официальная вики говорит так:
![image](https://user-images.githubusercontent.com/60313248/217279700-f6d4446c-e82e-4048-b2ea-cca8480069d7.png)
Сомневаюсь, что получится нормально собрать их без использования виртуальных машин. А пользователи остальных систем вполне могут
```
pip install -r requirements.txt
python D0CXUN7R4C3.py
```

**Comment by NICKNAME5166** [comment]
Клиентоориентированость - полный ноль, разрабы пидоры🥰🥰🥰

**Comment by NICKNAME5166** [comment]
А зачем это надо было делать под виндовс, если там и так все просто? На маке посложней, для него б и запилили.. или для андроида, на крайний случай)
